### ISSUE TITLE
Any advice on how to find the slave address?

### ISSUE THREAD

**Issue by SP410** [rosswarren/renogymodbus#1]

**Comment by rosswarren** [comment]
Hey, thanks for raising the issue. I am still working on the functionality, so haven't added a CLI for this yet. But could you please try:

* open a python REPL using `python` or `python3` command
* type `from renogymodbus import find_slaveaddress`
* type `find_slaveaddress('/dev/ttyUSB0')` (or whatever your port name is)

It will print the output.

For me, for my charge controller both `0` and `1` work, and for my battery I have two batteries and for some reason the addresses are `48` and `49`.

**Comment by SP410** [comment]
Thank you so much!  I say you had added the python script but had trouble figuring out how to use.  Strangely, my Rover 20A is at Address 17.
